export enum PUBLIC_ROUTES {
  LOGIN = "/login",
}

export enum PROTECTED_ROUTES {
  DASHBOARD = "/dashboard",
  PROJECTS = "/projects",
}

export const PRIMARY_PUBLIC = PUBLIC_ROUTES.LOGIN;
export const PRIMARY_PROTECTED = PROTECTED_ROUTES.DASHBOARD;
export const SECONDARY_PROTECTED = PROTECTED_ROUTES.PROJECTS;
