# Deploy Next.js site to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: './portfolio/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ./portfolio/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./portfolio/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./portfolio
        run: npm ci

      - name: Build with Next.js
        working-directory: ./portfolio
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: '/portfolio'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./portfolio/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4